name: Nix Flake Check On Commit

on:
  push:
    branches:
      - '**'

jobs:
  flake_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Nix
      uses: cachix/install-nix-action@v16

    - name: Nix Flake Check
      run: nix flake check
